import{a as g,S as y,i as h}from"./assets/vendor-BjRz3xa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const b="49795001-63fc88dd531083a7427250d55";async function L(r){return await g("https://pixabay.com/api/",{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const u=document.querySelector(".gallery"),d=document.querySelector(".loader");let o=null;function S(r){const{webformatURL:s,largeImageURL:a,tags:l,likes:e,views:t,comments:i,downloads:p}=r;return`<li class="gallery-item">
        <div>
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${s}" alt="${l}" />
        </a>
        </div>
        <ul class="gallery-sublist">
          <li class="gallery-subitem"><p class="sub-text">Likes</p><p class="sub-value">${e}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Views</p><p class="sub-value">${t}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Comments</p><p class="sub-value">${i}</p></li>
          <li class="gallery-subitem"><p class="sub-text">Downloads</p><p class="sub-value">${p}</p></li>
        </ul>
      </li>`}function v(r){const s=r.map(S).join("");u.insertAdjacentHTML("beforeend",s),o?o.refresh():o=new y(".gallery a",{captionsData:"alt",captionDelay:250})}function w(){u.innerHTML="",o&&(o.destroy(),o=null)}function c(){d.classList.remove("hidden")}function f(){d.classList.add("hidden")}const m={form:document.querySelector("form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery")};f();m.form.addEventListener("submit",x);function x(r){r.preventDefault(),m.gallery.innerHTML="",c();const s=r.target.elements.search.value.trim();if(!s){n("Please enter a search query");return}c(),w(),L(s).then(a=>{const l=a.data;if(!l.hits||l.hits.length===0){n("Sorry, no images found. Please try another query!");return}v(l.hits)}).catch(a=>{n("Failed to fetch images. Please try again later."),console.error("Error:",a)}).finally(()=>{f()}),r.target.reset()}function n(r){h.warning({message:r,titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",position:"topRight"})}
//# sourceMappingURL=index.js.map
